//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public Nullable<int> eventId { get; set; }
        public Nullable<int> communityId { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> initialDate { get; set; }
        public string authorId { get; set; }
    
        public virtual userInfo userInfo { get; set; }
        public virtual community community { get; set; }
        public virtual @event @event { get; set; }
    }
}
