//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventSubscribers
    {
        public int eventId { get; set; }
        public string userId { get; set; }
        public Nullable<bool> checkIn { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual userInfo userInfo { get; set; }
    }
}
