//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class inboxMessage
    {
        public int id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string receiver { get; set; }
        public string sender { get; set; }
    
        public virtual userInfo userInfo { get; set; }
        public virtual userInfo userInfo1 { get; set; }
    }
}
