//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice
    {
        public int id { get; set; }
        public Nullable<int> communityId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> initialDate { get; set; }
    
        public virtual community community { get; set; }
    }
}
