//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public question()
        {
            this.user_like = new HashSet<userInfo>();
        }
    
        public int id { get; set; }
        public string message { get; set; }
        public string authorId { get; set; }
        public Nullable<int> sessionId { get; set; }
        public Nullable<int> likes { get; set; }
    
        public virtual userInfo userInfo { get; set; }
        public virtual session session { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userInfo> user_like { get; set; }
    }
}
