//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public session()
        {
            this.question = new HashSet<question>();
        }
    
        public int id { get; set; }
        public Nullable<int> eventId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public System.DateTime initialDate { get; set; }
        public string speakerName { get; set; }
        public string lastName { get; set; }
        public string linkOfSpeaker { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    
        public virtual @event @event { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<question> question { get; set; }
    }
}
