//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Models.DTOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class surveyAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public surveyAnswer()
        {
            this.surveyChoiceAnswer = new HashSet<surveyChoiceAnswer>();
        }
    
        public int eventId { get; set; }
        public int questionId { get; set; }
        public string authorId { get; set; }
    
        public virtual surveyQuestion survey { get; set; }
        public virtual userInfo userInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<surveyChoiceAnswer> surveyChoiceAnswer { get; set; }
        public virtual surveyTextAnswer surveyTextAnswer { get; set; }
    }
}
